version: '3.8'

services:
  discord-webhook-proxy:
    build: .
    ports:
      - "8501:8501"
    volumes:
      # Mount config directory for persistent configuration
      - ./config:/app/config
      # Mount the actual config.yaml file
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

